config/routes.rb
Rails.application.routes.draw do
  root 'logins#welcome'
  get 'login', to: 'logins#new'
  post 'login',to: 'logins#create'
  post 'logout', to: 'logins#destroy'
  
  resources :matches
  resources :away_players
  resources :away_teams
  resources :contracts
  resources :home_players
  resources :home_teams
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/away_player.rb
class AwayPlayer < ApplicationRecord
  belongs_to :away_team
end

app/models/away_team.rb
class AwayTeam < ApplicationRecord
  has_many :matches
  has_many :away_players
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :home_player
  belongs_to :home_team

  validates :home_team_id, uniqueness: { scope: :home_player_id, :message=>"You already added this player!"}
end

app/models/home_player.rb
class HomePlayer < ApplicationRecord
  has_many :contracts, :dependent => :delete_all
  has_many :home_teams, through: :contracts
end

app/models/home_team.rb
class HomeTeam < ApplicationRecord
  belongs_to :user
  has_many :contracts
  has_many :home_players, through: :contracts
  has_many :matches

  validates_presence_of :name, :location
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :away_team
  belongs_to :home_team
end

app/models/user.rb
class User < ApplicationRecord
  has_many :home_teams
  validates_uniqueness_of :username
  has_secure_password
end

app/controllers/away_teams_controller.rb
class AwayTeamsController < ApplicationController
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController



  def new
    find_players
    @contract = Contract.new
    @your_teams = HomeTeam.all.select{|team| team.user_id == @logged_in_user_id}
  end

  def create
    find_players
    @your_teams = HomeTeam.all.select{|team| team.user_id == @logged_in_user_id}
    @contract = Contract.create(contract_params)
    @home_team = HomeTeam.find(@contract.home_team.id)
    if @contract.valid? && @home_team.home_players.length == 5
      redirect_to home_team_path(@contract.home_team)
    elsif @home_team.home_players.length < 5
      redirect_to new_contract_path
    else
      render :new
    end
  end



  private
  def contract_params
    params.require(:contract).permit(:home_team_id, :home_player_id)
  end

  def find_players
    @point_guards = HomePlayer.all.select {|player| player.position == "PG"}
    @shooting_guards = HomePlayer.all.select {|player| player.position == "SG"}
    @small_forwards = HomePlayer.all.select {|player| player.position == "SF"}
    @power_forwards = HomePlayer.all.select {|player| player.position == "PF"}
    @centers = HomePlayer.all.select {|player| player.position == "C"}
  end

end

app/controllers/home_teams_controller.rb
class HomeTeamsController < ApplicationController

  def index
    @teams = HomeTeam.select {|team| team.user_id == @logged_in_user_id}
  end

  def new
    @home_team = HomeTeam.new
    @users = []
    @users << @logged_in_user
  end

  def create
    @home_team = HomeTeam.create(home_team_params.merge(num_of_wins: 0, num_of_losses: 0))
    if @home_team.valid?
      redirect_to @home_team
    else
      render :new
    end
  end


  def show
    @home_team = HomeTeam.find(params[:id])
    @all_users = User.all.sort_by {|user| user.home_teams.first.num_of_wins}.reverse
  end

  def destroy
    Match.where(home_team_id: params[:id]).destroy_all
    HomeTeam.destroy(params[:id])
    redirect_to home_teams_path
  end



  private
  def home_team_params
    params.require(:home_team).permit(:name, :location, :user_id, :num_of_wins, :num_of_losses)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_login, only: [:new,:create, :welcome]

  def new

  end

  def welcome
    
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      log_in_user(@user.id)
      redirect_to home_teams_path
    else
      render :new
    end
  end

  def destroy
    log_out_user
    redirect_to root_path
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def new
    @match = Match.new
    @your_teams = HomeTeam.where(user_id: @logged_in_user_id)
  end

  def create
    @match = Match.create(match_params)
    find_winner
    redirect_to @match.home_team
  end

  def show
    @match = Match.find(params[:id])
  end

  def edit

  end



  private
  def match_params
    params.require(:match).permit(:home_team_id, :away_team_id)
  end

  def find_winner
    @home_values = @match.home_team.home_players.map do |player|
      player.value.to_i
    end
    @home_value_sum = @home_values.reduce{|sum, x| sum + x }

    @away_values = @match.away_team.away_players.map do |player|
      player.value.to_i
    end
    @away_value_sum = @away_values.reduce{|sum, x| sum + x }

    @total_values = @home_value_sum + @away_value_sum

    @home_odds = ((@home_value_sum.to_f / @total_values) * 100).round
    @away_odds = ((@away_value_sum.to_f / @total_values) * 100).round

    @odds_array = []

    @home_odds.times do
      @odds_array << "A"
    end

    @away_odds.times do
      @odds_array << "B"
    end

    @winner = @odds_array.sample
    if @winner == "A"
      @match.home_team.update_attributes(num_of_wins: (@match.home_team.num_of_wins + 1))
      flash[:win] = "Good job, you won!"
    else
      @match.home_team.update_attributes(num_of_losses: (@match.home_team.num_of_losses + 1))
      flash[:lose] = "You suck! You lost!"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new,:create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(check_params)
    if @user.valid?
      log_in_user(@user.id)
      redirect_to home_teams_path
    else
      render :new
    end
  end

  def destroy
    redirect_to controller: "sessions", action: "destroy"
  end


  private

  def check_params
    params.require(:user).permit(:username, :password)
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/away_players_helper.rb
module AwayPlayersHelper
end

app/helpers/away_teams_helper.rb
module AwayTeamsHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/home_players_helper.rb
module HomePlayersHelper
end

app/helpers/home_teams_helper.rb
module HomeTeamsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contracts/_form.html.erb
<ul style="color:red">
  <% @contract.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<div class="pick-players1">
  <%= form_for @contract do |form| %>
    Point Guard:
    <%= form.collection_select(:home_player_id, @point_guards, :id, :name, {}, {:class => "collect"})%>
    <br>
    <%= form.label :team %>
    <%= form.collection_select :home_team_id, @your_teams, :id, :name %>
    <br>
    <%= form.submit value = "Add Player"%>
  <% end %>
  <br>

  <%= form_for @contract do |form| %>
    Shooting Guard:
    <%= form.collection_select(:home_player_id, @shooting_guards, :id, :name, {}, {:class => "collect"})%>
    <br>
    <%= form.label :team %>
    <%= form.collection_select :home_team_id, @your_teams, :id, :name %>
    <br>
    <%= form.submit value = "Add Player"%>
  <% end %>
  <br>

  <%= form_for @contract do |form| %>
    Small Forward:
    <%= form.collection_select(:home_player_id, @small_forwards, :id, :name, {}, {:class => "collect"})%>
    <br>
    <%= form.label :team %>
    <%= form.collection_select :home_team_id, @your_teams, :id, :name %>
    <br>
    <%= form.submit value = "Add Player"%>
  <% end %>
  <br>
</div>

<div class="pick-players2">
  <%= form_for @contract do |form| %>
    Power Forward:
    <%= form.collection_select(:home_player_id, @power_forwards, :id, :name, {}, {:class => "collect"})%>
    <br>
    <%= form.label :team %>
    <%= form.collection_select :home_team_id, @your_teams, :id, :name %>
    <br>
    <%= form.submit value = "Add Player"%>
  <% end %>

  <%= form_for @contract do |form| %>
    Center:
    <%= form.collection_select(:home_player_id, @centers, :id, :name, {}, {:class => "collect"})%>
    <br>
    <%= form.label :team %>
    <%= form.collection_select :home_team_id, @your_teams, :id, :name %>
    <br>
    <%= form.submit value = "Add Player"%>
  <% end %>
</div>

app/views/contracts/new.html.erb
<h1 class="start">Draft Your Players</h1>
<h3 class="start">(Pick 1 Player From Each Position)</h3>
<h3 style = "margin-left: 25px;">Start by picking a Point Guard and pressing "Add Player", then move on to the next position.</h3>


<%= render "form" %>

app/views/home_teams/_footer.html.erb
<%if @logged_in%>
  Hello, <%= @logged_in_user.username.titleize%>, you're logged in!
<%end%>

app/views/home_teams/_form.html.erb
<%= form_for @home_team do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br>
  <%= form.label :location %>
  <%= form.text_field :location %>
  <br>
  Owner:
  <%= form.collection_select :user_id, @users, :id, :username %>
  <br>
  <%= form.submit %>
<% end %>

app/views/home_teams/_header.html.erb
<header class="right">
  <nav>
    <div>
      <% if @home_team %>
        Welcome To <%= @home_team.name.titleize %>'s Team Page!
      <% end %>
    </div>
  </nav>
</header>

app/views/home_teams/index.html.erb
  <div class="container">

    <h1 style="text-align:center;">Your Teams:</h1>

    <h2>
      <ol>
        <% @teams.each do |team| %>
          <li>
            <%= link_to "#{team.name}", team %>
            <%= button_to("Delete Team", team, method: :delete, :id => "delete") %>
          </li>
        <% end %>
      </ol>
    </h2>
    <%= button_to "Create A Team", new_home_team_path, method: :get %>
  </div>

app/views/home_teams/new.html.erb
<div class="container">
  <h1 style="text-align:center">Create Your Team!</h1>
  <%= render "form" %>
</div>

app/views/home_teams/show.html.erb
<% if flash[:win] %>
  <div class="win">
    <%= flash[:win] %>
  </div>
<% end %>
<% if flash[:lose] %>
  <div class="lose">
    <%= flash[:lose] %>
  </div>
<% end %>

<div class="flex">
  <div class="lineup">
    <h3>Your Starting Lineup:</h3>
    <% if @home_team.home_players.length > 0 %>
      <table>
        <tr>
          <th>Player Name</th>
          <th>Position</th>
        </tr>
        <tr>
          <td><%= @home_team.home_players.first.name %></td>
          <td><%= @home_team.home_players.first.position %></td>
        </tr>
        <tr>
          <td><%= @home_team.home_players.second.name %></td>
          <td><%= @home_team.home_players.second.position %></td>
        </tr>
        <tr>
          <td><%= @home_team.home_players.third.name %></td>
          <td><%= @home_team.home_players.third.position %></td>
        </tr>
        <tr>
          <td><%= @home_team.home_players.fourth.name %></td>
          <td><%= @home_team.home_players.fourth.position %></td>
        </tr>
        <tr>
          <td><%= @home_team.home_players.fifth.name %></td>
          <td><%= @home_team.home_players.fifth.position %></td>
        </tr>
      </table>

    <h3>Your Record: (<%= @home_team.num_of_wins %>-<%= @home_team.num_of_losses %>)</h3>
    <% end %>
    <div id="rei">
      <%= button_to "Add Players To Your Roster", new_contract_path, method: :get %>
      <%= button_to "Play A Game", new_match_path, method: :get%>
    </div>
  </div>


  <div class="leaderboard">
    <table>
      <h3>LeaderBoard:</h3>
      <tr>
        <th>Username</th>
        <th>Record</th>
      </tr>
      <% @all_users.each do |user| %>
        <tr>
          <td><%= user.username.titleize %></td>
          <td>(<%= user.home_teams.first.num_of_wins %>-<%= user.home_teams.first.num_of_losses %>)</td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/matches/_form.html.erb
<div class="container">
  <%= form_for @match do |form| %>
    Home Team(PICK YOUR TEAM):
    <%= form.collection_select(:home_team_id, @your_teams, :id, :name, {}, {:class => "collect"}) %>
    <br>
    Away Team:
    <%= form.collection_select(:away_team_id, AwayTeam.all, :id, :name, {}, {:class => "collect"}) %>
    <br>
    <%= form.submit value="Start Game"%>
  <% end %>
</div>

app/views/matches/new.html.erb
<h1>Choose Your Team and An Opponent:</h1>

<%= render "form" %>

app/views/matches/show.html.erb
<%= @match.home_team.num_of_wins  %>



<%= @match.home_team.num_of_losses %>

app/views/users/index.html.erb
<h1>All Users</h1>
<%= @user.username %>

app/views/users/new.html.erb
<% @user.errors.full_messages.each do |message| %>
  <h2 style="color:#930000; margin-left: 20px;"><%= message %></h2>
<% end %>

<div class="container">
  <h1>New User Signup</h1>

  <%= form_for @user do |f|%>
    <%=f.label :username%>
    <%=f.text_field :username%>
    <br>
    <%=f.label :password%>
    <%=f.password_field :password%>
    <br>
    <%=f.submit%>
  <%end%>
</div>